conference_app/conference_app/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("conferences/", include('conferences.urls')),
    path("events/", include("events.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

conference_app/conferences/urls.py
from.views import ConferenceListView, ConferenceDetailView, ConfeneceLikeView
from django.urls import path





urlpatterns = [
    # Visi views kurie yra ne funkcijos, o klases,
    # juos kvieciam su papildoma as_view()
    path("", ConferenceListView.as_view()), # /conferences/
    path( "<int:pk>/", ConferenceDetailView.as_view(), name = "conference-detail" ), # /conferences/1/, /conferences/10/
    path("like/<int:konferencijos_id>/", ConfeneceLikeView.as_view(), name = "conference-like"),
]

conference_app/events/urls.py
from django.urls import path
from events.views import (
    EventDetailView,
    RegisterVisitorView,
    UserEventList,
)

urlpatterns = [
    # /events/2/
    path( '<int:pk>/', EventDetailView.as_view(), name = "event-detail" ),
    path( 'register/<int:renginio_id>/', RegisterVisitorView.as_view(), name = "register-visitor" ),
    path('my-events/', UserEventList.as_view(), name = "user-events"),
    ]

conference_app/conferences/models.py
# Create your models here.
import self as self
from django.contrib.auth.models import User
from django.db import models

# a. Konferencija – turi datą nuo-iki, pavadinimą,
# [sukūrimo ir modifikavimo datos (auto_now, auto_now_add)]
class Conference( models.Model ):
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField( max_length = 100 )
    picture = models.ImageField(null= True)
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    def __str__( self ):
        return self.title





class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

# CREATE TABLE Confereces (
#   id INT PRIMARY KEY AUTO_INCREMENT,
#   start_date ...

conference_app/events/models.py
from django.contrib.auth.models import User
from django.db import models
from conferences.models import Conference


# Create your models here.
from django.db import models
from conferences.models import Conference

# Create your models here.
class Event( models.Model ):
    date = models.DateTimeField( null = True )
    title = models.CharField( max_length = 100 )
    # TODO:Istrinti ateityje
    visitors = models.IntegerField( default = 0 )

    conference = models.ForeignKey( Conference, on_delete = models.CASCADE )

    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )




class EventRegistration (models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE, )
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)

conference_app/conferences/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from .models import Conference, Like


# Create your views here.



# 	Sukurkite ListView, kuris atvaizduotų visas konferencijas
class ConferenceListView(ListView):
    model = Conference
    # Alternatyva ListView klasei:
    # def conference_list( request ):
    #     conferences = Conference.objects.all()
    #     return render( request, "conferences/conference_list.html", { "object_list": conferences })

class ConferenceDetailView (DetailView):
    model = Conference
    # Alternatyva DetailView
    # def conference_detail( request, pk ): # pk ateina iš urls failo: path( "<int:pk>/", ... )
    #     conference = get_object_or_404( Conference, pk = pk )
    #     return render( request, "conferences/conference_detail.html", { "object": conference } )
class ConfeneceLikeView(View):
    def get(self, request, conferencijos_id):
        if not request.user.is_authenticated:
            return redirect('login')
        conference = get_object_or_404(Conference, id=conferencijos_id)
        laiku_kiekis = Like.objects.filter(conference=conference, user=request.user).count()
        if laiku_kiekis > 0:
            return HttpResponse("Jus jau prisiregistravote")

        # event.visitors += 1  # pridedam viena visitor
        # event.save()  # issaugo informacija
        registration = Like()
        registration.event = conference
        registration.user = request.user
        registration.save()
        redirect('conference-detail', conferencijos_id)

conference_app/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView
from events.models import Event, EventRegistration


# Create your views here.
class EventDetailView( DetailView):
    model = Event
    context_object_name = "renginys" #pervadinam event renginiu
class RegisterVisitorView(LoginRequiredMixin, View):

    def get(self, request, renginio_id):
        event = get_object_or_404(Event, id=renginio_id)
        registraciju_kiekis = EventRegistration.objects.filter(event = event, user = request.user). count()
        if registraciju_kiekis>0:
            return HttpResponse ("Jus jau prisiregistravote")

        #event.visitors += 1  # pridedam viena visitor
       # event.save()  # issaugo informacija
        registration = EventRegistration()
        registration.event = event
        registration.user = request.user
        registration.save()



        return redirect (f"/events/{renginio_id}")
class UserEventList (View):

    def get (self, request):
        if not request.user.is_autenticated: # Apsauga nuo neprisijungusiu vartotoju
            return redirect('login')
        user_events = EventRegistration.objects.filter(
        user = request.user)

        return render(
            request, "event/user_events.html",
                     {"object_list":user_events}
        )

conference_app/conferences/templates/conferences/conference_detail.html
{% extends "base.html" %}

{% block "title" %}
    {{ object.title }}
{% endblock %}

{% block "content" %}
    <h1>{{ object.title }}</h1>
 {% if object.picture %}
 <img src="{{ object.picture.url}}"> height="150px">
{% endif %}
    <div>Pradzia: {{ object.start_date }}</div>
    <div>Pabaiga: {{ object.end_date }}</div>
{{object.like_set.count }}
    <h2>Renginiai:</h2>
    <ol>
        {% for event in object.event_set.all %}
            <li>
                <a href="{% url 'event-detail' event.id %}">
                    {{ event.title }}
                </a>
                ({{ event.date }})
                {% if user.is_authenticated %}
                Dalyvauja {{event.visitors}}
                {% endif %}
            </li>
        {% endfor %}
    </ol>
{% endblock %}

conference_app/conferences/templates/conferences/conference_list.html
{% extends "base.html" %}

{% block "title" %}
Konferencijų sąrašas
{% endblock %}

{% block "content" %}
    <ol>
        {% for conference in object_list %}
            <li>
                <a href="{% url 'conference-detail' conference.id %}">{{ conference.title }}</a>
<!--            <a href="/conferences/{{ conference.id }}">{{ conference.title }}</a>-->
                ({{ conference.start_date }} - {{ conference.end_date }})
            </li>
        {% endfor %}
    </ol>
{% endblock %}

conference_app/events/templates/events/event_detail.html
{% extends "base.html" %}

{% block "title" %}
  Renginiai
{% endblock %}

{% block "content" %}
  <h1>Renginys: {{ renginys.title }}</h1>

  <div>Pradžia: {{ renginys.date }}</div>
  <div>Jau dalyvauja: {{ renginys.eventregistration_set.count }}</div>

  <a href="/events/register/{{ renginys.id }}">Užsiregistruoti</a>
  <a href="{% url 'register-visitor' renginys.id %}">Užsiregistruoti</a>
{% endblock %}

conference_app/events/templates/events/user_events.html
{% extends "base.html" %}

{% block "title" %} Mano renginiai {% endblock %}

{% block "content" %}

    <h1>Mano renginiai:</h1>

    <ul>
        {% for registracija in object_list %}
            <li>
                <a href="{% url 'event-detail' registracija.event.id %}">
                    {{ registracija.event.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

conference_app/templates/base.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block "title" %}Konferencijos{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Konferencijos</a>
      </div>
    </nav>
    <div class="container py-5">
        {% if user.is_authenticated %}
            Esate prisijungęs kaip {{ user.username }}
        {% else %}
            <a href="{% url 'login' %}">Prisijunkite</a>
        {% endif %}

        {% block "content" %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>